### ISSUE TITLE
Regions not being honored

### ISSUE THREAD

**Issue by Custos** [spulec/PyQS#26]
I've set regions in both the boto config file and environment variable.  Queues are still being placed in us-east-1 instead of us-west-2

**Comment by andrewgross** [comment]
Thanks for reporting this.  How are you calling PyQS, as an import or on the command line?

**Comment by Custos** [comment]
Import.

**Comment by andrewgross** [comment]
Hey, if it is not too much trouble, can you include a code snippet showing how you import and call PyQS?

**Comment by Custos** [comment]
Just using your code snippet causes the issue for me (http://pastebin.com/WqJH9Ct1)

Honestly, before you spend too much time on this let me dig in one more time this weekend and make sure it’s not a stupid error, I was working on it at 4 AM :-)

AWS Config Files:

ubuntu@ip-10-18-9-116:~/.aws$ ls
config  credentials

ubuntu@ip-10-18-9-116:~/.aws$ cat config
region=us-west-2

ubuntu@ip-10-18-9-116:~/.aws$ cat credentials
[default]
# The access key for your AWS account
aws_access_key_id=<REDACTED>

# The secret key for your AWS account
aws_secret_access_key=<REDACTED>

**Comment by andrewgross** [comment]
I dug in to this a bit more, I don't think it is an issue on your end.  For tasks we call `boto.connect_sqs()`.  This creates a connection using `SQSConnection`, found [here](https://github.com/boto/boto/blob/develop/boto/sqs/connection.py#L32-L63).  This uses a default region of `us-east-1` if we do not specify a region.  I don't believe it ever checks any of the other settings.  However, if we use the `boto.sqs.connect_to_region()` interface, we can specify our region properly.  I will check in to how we are supposed to properly find the correct region from the environment.

**Comment by Custos** [comment]
Sorry I fell by the way side on this, I can dig in on my end, and will update over next few weeks when I validate cause.

**Comment by andrewgross** [comment]
Hey,

Any update on this? I am going to take another pass at figuring out if there is something we are not respecting about regions just in case.

**Comment by andrewgross** [comment]
Hey,

Any update on this? I am going to take another pass at figuring out if there is something we are not respecting about regions just in case.

**Comment by vsapucaia** [comment]
I was having the same issue but I made it work by configuring ~/.boto file like the code below. It's weird but it only works if "default_*" and "sqs_*" region and endpoint are configured with the same values

[Credentials]
aws_access_key_id = <key_id>
aws_secret_access_key = <secret>
default_region_name = eu-central-1
default_region_endpoint = sqs.eu-central-1.amazonaws.com

[Boto]
sqs_region_name = eu-central-1
sqs_region_endpoint = sqs.eu-central-1.amazonaws.com
