### ISSUE TITLE
Memory Leak and Failed Shutdown

### ISSUE THREAD

**Issue by andrewgross** [spulec/PyQS#44]
When running some long running PyQS processes, we noticed that we had some orphaned processes that persisted every time we restarted that Manager Worker.  The following investigation with @nadlerjessie revealed the following:

1. All orphaned (PPID = 1) processes were Reader Workers that had failed to shut down 
2. The ReaderWorker was stuck on a `futex` call waiting to put messages onto the internal queue
3. Despite the `queue.put` operation using a timeout, it would never timeout
4. Eventually our supervising process `supervisord` would get tired of waiting and `SIGKILL` the Manager Worker
5. The Process Workers would discover their parent had die and shut themselves down
6. The Reader Worker would forever hang on the `futex` and never shut down properly.

This seems to be related to the other end of the queue pipe holding the `futex` and shutting down anyways.  In our environment our internal queue was very often full and the Reader Worker was unable to push to the internal queue since it had hit its size limit.  It was often discarding downloaded messages since they had exceeded their visibility timeout.

Possible Solutions:
1. Explicitly release our lock on the internal queue before shutting down the Process Workers.
2. Instead of relying on timeouts, rewrite using a while/True loop with `time.sleep` and `queue.put_no_wait`.

Open Questions:
1. Why is the `futex` never being released even though the Process Workers are exiting in an expected fashion.  Perhaps the `futex` lock is actually tied to the Manager Worker?  Though this would mean we should occasionally see some orphaned Process Workers as well.
2. Can we duplicate this with tests?

**Comment by andrewgross** [comment]
Maybe I am misinterpreting how the signals are being handled when the Manager Worker sets the stop flag.

**Comment by andrewgross** [comment]
If we can get a reproducible test case it would be worth seeing if sending the `stop` signal to all child processes before calling `join` would fix the issue.

**Comment by andrewgross** [comment]
Possible test:

1. Reader Worker endlessly fills an internal queue with tasks containing a 10-60 second sleep (or non-interruptible work) while keeping a 3 second timeout on the `futex`.
2. Process Workers chew these tasks as expected
3. Initiate Shutdown and wait.
4. Somehow cleanup orphaned procs

**Comment by andrewgross** [comment]
Also our logging can get screwy during shutdown, Reader Worker started reporting the Manager Worker's PID as its own in logging.  May be due to scoping issues with `os` ?

**Comment by andrewgross** [comment]
Working on this in #45

**Comment by MyDigitalLife** [comment]
@andrewgross As the refered pull request is closed and merged is this issue solved?

**Comment by andrewgross** [comment]
For this issue yes.  This is not a guarantee that there are not other memory leaks, but this issue was resolved.
