### ISSUE TITLE
Not reading tasks

### ISSUE THREAD

**Issue by kmarsh** [spulec/PyQS#58]
This looks like a perfect fit for a small project that doesn't require the complexity of Celery, however in my simple tests I'm not able to get any tasks to run. I setup a simple app to process jobs from an SQS queue, and put a task in there but the workers never seem to see/run it:

```python
import logging
from pyqs import task

@task(queue='va-images')
def process(message):
  print("HERE")
  print(message)
```

There is a message in the queue on SQS:

![image](https://user-images.githubusercontent.com/100/56741449-e8094400-6740-11e9-9c27-54070e5c583a.png)

I just see the following output, over and over (lots depending on `--concurrency` passed in...)

```
[INFO]: Starting PyQS version 0.1.2
[INFO]: Loading Queues:
[INFO]: [Queue]	va-images
[INFO]: Found credentials in environment variables.
[INFO]: Found matching SQS Queues: ['https://queue.amazonaws.com/844333092237/va-images']
[INFO]: Running ReadWorker: https://queue.amazonaws.com/844333092237/va-images, pid: 9
[INFO]: Parent process has gone away, exiting process 9!
[INFO]: Running ProcessWorker, pid: 11
[INFO]: Parent process has gone away, exiting process 11!
[INFO]: Running ProcessWorker, pid: 12
[INFO]: Parent process has gone away, exiting process 12!
[INFO]: Running ProcessWorker, pid: 13
[INFO]: Parent process has gone away, exiting process 13!
[INFO]: Running ProcessWorker, pid: 10
[INFO]: Parent process has gone away, exiting process 10!
[INFO]: Running ProcessWorker, pid: 15
[INFO]: Running ProcessWorker, pid: 16
[INFO]: Parent process has gone away, exiting process 16!
[INFO]: Parent process has gone away, exiting process 15!
[INFO]: Running ProcessWorker, pid: 17
[INFO]: Parent process has gone away, exiting process 17!
[INFO]: Running ProcessWorker, pid: 14
[INFO]: Parent process has gone away, exiting process 14!
[INFO]: Running ProcessWorker, pid: 18
[INFO]: Parent process has gone away, exiting process 18!
[INFO]: Running ProcessWorker, pid: 19
[INFO]: Parent process has gone away, exiting process 19!
[INFO]: Running ProcessWorker, pid: 20
```

I'm running in Docker, not sure if that makes a difference or not:

```Dockerfile
FROM python:3.7-alpine

RUN apk add --update \
  imagemagick \
  && rm -rf /var/cache/apk/*

COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

COPY . /app

WORKDIR /app

CMD ["pyqs", "va-images", "--concurrency", "20", "--log-level", "INFO"]
```

Any pointers/help appreciated!

**Comment by spulec** [comment]
Can you run with a log level of DEBUG and post the logs please?

**Comment by kmarsh** [comment]
I think I found out what was causing this, since I was running in "raw" Docker without a supervisor the check for parent process was always returning 1, so the logic had thought the parent process had gone away. I commented out that bit in https://github.com/spulec/PyQS/compare/master...kmarsh:docker-fix and it fixed it for me, but I don't know enough about the rest of the parent/child worker architecture to attempt a better fix.

**Comment by spulec** [comment]
Ah, right. That has bit me before too. For now, I have added a warning to the README. I don't know if there is a more proper way to handle this

**Comment by spulec** [comment]
If you get a chance to test out the fix in https://github.com/spulec/PyQS/pull/59 that would be great.
