### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by Tenzer** [spulec/PyQS#63]
I've noticed that PyQS breaks when run on Python 3.8, specifically due to the use of `time.clock()` in `worker.py`, which has been removed in 3.8.

The ideal way to fix this would be to use `time.monotonic()` instead, but that's not available in Python < 3.5, and I can see Python 2.7 is being tested in the Travis configuration, so perhaps the easier solution would be to use `time.time()` - although it has the caveat that time may go backwards.

An alternative would be to use a third-party library to add `time.monotonic()` to the older Python releases, such as https://pypi.org/project/monotonic/. Do you have a preferred course of action on this?

**Comment by spulec** [comment]
I can't see a reason why `time.time()` wouldn't be sufficient.

**Comment by Tenzer** [comment]
Alright, I have made https://github.com/spulec/PyQS/pull/64 to fix this.

**Comment by spulec** [comment]
Closed with https://github.com/spulec/PyQS/pull/64
