### ISSUE TITLE
impossible to decode s3 event message

### ISSUE THREAD

**Issue by tvallois** [spulec/PyQS#73]
Hello !

First, thanks for the library you did guys ! :100: 

We're trying to create a worker which decode s3 event message. The message's format is described here: https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

However, PyQS recognize those messages as Celery message as it's clearly not.
Looking at source code:
```python
def decode_message(message):
    message_body = message['Body']
    json_body = json.loads(message_body)
    if 'task' in message_body:
        return json_body
    else:
        # Fallback to processing celery messages
        return decode_celery_message(json_body['body'])

```
You check that "task" is in the message body. I'm not sure to understand why. Is it the message format when you send message in a sqs from pyqs?

I'd be happy to contribute to fix this issue if it's one :)

**Comment by tvallois** [comment]
Damn, haven't checked the other issues... It's seems related to #69 ...

**Comment by spulec** [comment]
Yes, going to close in favor of #69 since I think they are the same.
